server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:                                             ## 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource              # 数据源 HikariCP
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456               # 本地数据库
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 15           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DatebookHikariCP     # 连接池名字
      max-lifetime: 28740000          # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout参数（show variables like '%timeout%';） -->
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 10485760      # 文件上传配置 限制10m
      max-request-size: 10485760   # 文件上传配置 限制10m

  mybatis:
    type-aliases-package: cn.cong.pojo                     # 所有POJO类所在包路径
    mapper-locations: classpath:mapper/*.xml                  # mapper映射文件

  ############################################################
  #
  # mybatis mapper 配置
  #
  ############################################################
  # 通用 Mapper 配置
  mapper:
    mappers: cn.cong.mapper.MyMapper
    not-empty: false
    identity: MYSQL
  # 分页插件配置
  pagehelper:
    helperDialect: mysql
    supportMethodsArguments: true
    params: count=countSql